version: "3"

services:
  mysql:
    image: mysql:8.0.11
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=pass

  postgres:
    image: postgres:10.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres